// Load-verified office invoice email — HTML cover note.
//
// Fires at load_verified — i.e. Rick has verified the load on the dock
// and the materials are about to leave the warehouse. The office gets
// this as the materials-issued invoice of record.
//
// 2026-05-20: this HTML body is now a SHORT cover note. The full
// invoice detail (line items, unit prices, total) lives in the PDF
// attachment generated by load-verified-invoice-pdf.ts. Owner asked
// for "a PDF invoice with some details in the body", so we keep the
// summary keys (invoice id, job, total) inline for fast inbox scanning
// and direct the reader to the attachment for the rest.
//
// PRICE ONLY. No cost-side data ever lives on this email. See
// feedback_purchase_price_visibility — cost reaches owner / admin /
// office / manager / Richard via separate reports, never on the invoice.
// JN reps and customers must be safe to forward this to.

import {
  esc,
  renderFooter,
  renderHeader,
  renderKVTable,
  wrapDocument,
  COLORS,
} from './shared';

export interface LoadVerifiedInvoiceEmailData {
  ticketId: string;
  invoiceId: string;
  jobNumber: string;
  customerName: string;
  address: string;
  salesRepName: string;
  verifiedByName: string;
  /** ISO string or anything `new Date(...)` accepts. */
  verifiedAt: string;
  materials: Array<{
    name: string;
    qty: number;
    unit?: string;
    unitPrice: number;
    linePrice: number;
  }>;
  totalPrice: number;
  notes?: string;
}

/** Subject line: invoice ID first for easy scanning in the inbox. */
export function loadVerifiedInvoiceSubject(data: LoadVerifiedInvoiceEmailData): string {
  return `Invoice ${data.invoiceId} — ${data.jobNumber} ${data.customerName}`;
}

function fmtMoney(n: number): string {
  if (typeof n !== 'number' || !isFinite(n)) return '$0.00';
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

// `verifiedByName` / `verifiedAt` are no longer rendered in the cover
// note (they live in the PDF). Kept on the data interface because the
// PDF generator still uses them.

export function renderLoadVerifiedInvoiceEmail(data: LoadVerifiedInvoiceEmailData): string {
  // Short summary block — invoice id, job, total. Just enough for the
  // recipient to triage in the inbox; the full detail is in the PDF.
  const kv = renderKVTable({
    rows: [
      { label: 'Invoice', value: data.invoiceId },
      { label: 'Job', value: `${data.jobNumber} — ${data.customerName}` },
      { label: 'Total', value: fmtMoney(data.totalPrice) },
    ],
  });

  const content = `
    ${renderHeader({ title: `Invoice ${esc(data.invoiceId)}` })}

    <tr>
      <td class="rcrs-pad" style="padding:8px 32px 4px 32px;font-family:${COLORS.FONT_STACK};">
        <p style="margin:0 0 12px 0;font-size:14px;color:${COLORS.TEXT};line-height:1.6;">
          Materials for the job below have been loaded and verified at the warehouse. Stock has been deducted and this invoice is the record of materials issued.
        </p>
        <p style="margin:0;font-size:14px;color:${COLORS.TEXT};line-height:1.6;">
          The full invoice — line items, unit prices, and total — is attached as a PDF.
        </p>
      </td>
    </tr>

    <tr>
      <td class="rcrs-pad" style="padding:8px 32px 0 32px;">
        ${kv}
      </td>
    </tr>

    <tr>
      <td class="rcrs-pad" style="padding:16px 32px 24px 32px;font-family:${COLORS.FONT_STACK};">
        <p style="margin:0;font-size:12px;color:${COLORS.MUTED};line-height:1.6;">
          Pricing only. Material cost-side reporting is recorded separately in the office, admin, and manager reports and is not shown here.
        </p>
      </td>
    </tr>

    ${renderFooter()}
  `;

  return wrapDocument({
    preheader: `Invoice ${data.invoiceId} — ${fmtMoney(data.totalPrice)} — ${data.jobNumber} ${data.customerName}`,
    content,
  });
}
