$routes = @(
    "/api/admin/auth",
    "/api/admin/customer-portal",
    "/api/admin/geocode-sync",
    "/api/admin/jobnimbus",
    "/api/admin/jobnimbus/contacts",
    "/api/admin/jobnimbus/estimates",
    "/api/admin/jobnimbus/jobs",
    "/api/admin/jobnimbus/sync",
    "/api/admin/jobnimbus/sync-status",
    "/api/admin/jobnimbus/tasks",
    "/api/admin/jobnimbus/test",
    "/api/admin/lead-distro/config",
    "/api/admin/lead-distro/history",
    "/api/admin/lead-distro/preview",
    "/api/admin/mine-response-times",
    "/api/admin/populate-geocoded",
    "/api/admin/portal-management",
    "/api/admin/portal-settings",
    "/api/admin/response-times",
    "/api/admin/settings",
    "/api/admin/sheets-health",
    "/api/admin/system",
    "/api/admin/system/api-keys",
    "/api/admin/system/audit-log",
    "/api/admin/system/features",
    "/api/admin/system/maintenance",
    "/api/admin/team-members",
    "/api/admin/training-stats",
    "/api/admin/upload",
    "/api/analytics/page-views",
    "/api/analytics/profile-views",
    "/api/analytics/response-times",
    "/api/auth/pin",
    "/api/bible-verse",
    "/api/breakdown",
    "/api/breakdown/search",
    "/api/calendar/appointments",
    "/api/calendar/events",
    "/api/calendar/reminders",
    "/api/calendar/schedule",
    "/api/calendar/slots",
    "/api/calendar/teamup",
    "/api/calls",
    "/api/calls/analytics",
    "/api/calls/webhook",
    "/api/chat",
    "/api/cms/blog",
    "/api/cms/images",
    "/api/cms/setup",
    "/api/cms/team",
    "/api/command-center/agents",
    "/api/command-center/calls",
    "/api/command-center/competition",
    "/api/command-center/financial",
    "/api/command-center/insights",
    "/api/command-center/inventory",
    "/api/command-center/meetings",
    "/api/command-center/meetings/announcements",
    "/api/command-center/meetings/leaderboard",
    "/api/command-center/meetings/stats",
    "/api/command-center/rep-comparison",
    "/api/command-center/sales",
    "/api/command-center/stats",
    "/api/command-center/team",
    "/api/command-center/team-access",
    "/api/command-center/trends",
    "/api/contact",
    "/api/cron/check-lead-timers",
    "/api/cron/publish-blog",
    "/api/customer/auth",
    "/api/customer/dashboard",
    "/api/customer/delivery-status",
    "/api/customer/generate-token",
    "/api/customer/messages",
    "/api/customer/portal-analytics",
    "/api/customer/portal-log",
    "/api/customer/upload",
    "/api/dashboard/leads",
    "/api/documents",
    "/api/email-capture",
    "/api/forms/careers",
    "/api/forms/contact",
    "/api/forms/referral",
    "/api/hailrecon",
    "/api/honeypot",
    "/api/invoices",
    "/api/invoices/generate",
    "/api/jobnimbus/search",
    "/api/jobs/create",
    "/api/leads",
    "/api/leads/config",
    "/api/leads/contact-made",
    "/api/leads/distribute",
    "/api/leads/enrich",
    "/api/leads/metrics",
    "/api/leads/nearby",
    "/api/leads/new",
    "/api/leads/preview",
    "/api/leads/response-timer",
    "/api/leads/search",
    "/api/leads/verify-customer",
    "/api/notifications",
    "/api/notifications/groupme",
    "/api/notifications/preferences",
    "/api/notifications/send-portal",
    "/api/portal/ai-chat",
    "/api/portal/appointments",
    "/api/portal/auth",
    "/api/portal/billing",
    "/api/portal/billing/pdf",
    "/api/portal/blog",
    "/api/portal/blog/approve",
    "/api/portal/blog/pending",
    "/api/portal/blog/publish",
    "/api/portal/chat/customer-message",
    "/api/portal/chat/dm",
    "/api/portal/chat/groups",
    "/api/portal/chat/members",
    "/api/portal/chat/messages",
    "/api/portal/chat/quiet-hours",
    "/api/portal/customer-settings",
    "/api/portal/customers",
    "/api/portal/dashboard",
    "/api/portal/deliveries",
    "/api/portal/delivery",
    "/api/portal/delivery/ai-agent",
    "/api/portal/delivery/invoices",
    "/api/portal/delivery/iot",
    "/api/portal/delivery/job-breakdowns",
    "/api/portal/delivery/photos",
    "/api/portal/delivery/reminders",
    "/api/portal/delivery/settings",
    "/api/portal/delivery/smart-workflow",
    "/api/portal/delivery/work-orders",
    "/api/portal/drivers",
    "/api/portal/generate",
    "/api/portal/inventory",
    "/api/portal/inventory/history",
    "/api/portal/inventory/management",
    "/api/portal/inventory/reconciliation",
    "/api/portal/invoices",
    "/api/portal/jobnimbus",
    "/api/portal/jobnimbus/commissions",
    "/api/portal/jobnimbus/documents",
    "/api/portal/jobnimbus/metrics",
    "/api/portal/jobnimbus/my-contacts",
    "/api/portal/jobnimbus/my-jobs",
    "/api/portal/jobnimbus/notes",
    "/api/portal/jobnimbus/update-status",
    "/api/portal/jobs",
    "/api/portal/leads",
    "/api/portal/locations",
    "/api/portal/material-orders",
    "/api/portal/monday-notes",
    "/api/portal/monday-notes/announcements",
    "/api/portal/monday-notes/approve",
    "/api/portal/monday-notes/summary",
    "/api/portal/monday-notes/upload",
    "/api/portal/orders",
    "/api/portal/orders/workflow",
    "/api/portal/performance",
    "/api/portal/pricing",
    "/api/portal/pricing/alerts",
    "/api/portal/pricing/audit",
    "/api/portal/pricing/verify",
    "/api/portal/profile",
    "/api/portal/profile/approve",
    "/api/portal/profile/pending",
    "/api/portal/rep-availability",
    "/api/portal/rep-preferences",
    "/api/portal/restock",
    "/api/portal/roof-measure",
    "/api/portal/schedule",
    "/api/portal/storm-report/share",
    "/api/portal/sync",
    "/api/portal/tasks",
    "/api/portal/tickets",
    "/api/portal/tickets/checklist",
    "/api/portal/tickets/notify",
    "/api/portal/tickets/photos",
    "/api/portal/training",
    "/api/portal/training/modules",
    "/api/portal/training/quiz-submit",
    "/api/portal/training/sales",
    "/api/portal/transactions",
    "/api/portal/users",
    "/api/portal/warehouse",
    "/api/portal/weekly-numbers",
    "/api/portal/workflow",
    "/api/profile",
    "/api/profile/approve",
    "/api/profile/images",
    "/api/profile/my-edits",
    "/api/profile/pending",
    "/api/profile/pending-count",
    "/api/profile/reject",
    "/api/profile/reviews",
    "/api/profile/submit-edit",
    "/api/referral",
    "/api/roof-measure",
    "/api/roof-report",
    "/api/sheets/commissions",
    "/api/sheets/customers",
    "/api/sheets/inventory",
    "/api/sheets/sync",
    "/api/storm-report",
    "/api/team-members",
    "/api/webhooks/groupme",
    "/api/webhooks/jobnimbus"
)

$htmlRoutes = @()
$jsonCount = 0

foreach ($route in $routes) {
    try {
        $resp = Invoke-WebRequest -Uri "http://localhost:3000$route" -Method GET -TimeoutSec 10 -UseBasicParsing -ErrorAction Stop
        $body = $resp.Content.Substring(0, [Math]::Min(100, $resp.Content.Length))
        if ($body -match "<!DOCTYPE|<html|<head") {
            $htmlRoutes += "$route|$($resp.StatusCode)|HTML"
        } else {
            $jsonCount++
        }
    } catch {
        if ($_.Exception.Response) {
            $status = [int]$_.Exception.Response.StatusCode
            $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
            $body = $reader.ReadToEnd()
            $reader.Close()
            $snippet = $body.Substring(0, [Math]::Min(100, $body.Length))
            if ($snippet -match "<!DOCTYPE|<html|<head") {
                $htmlRoutes += "$route|$status|HTML"
            } else {
                $jsonCount++
            }
        } else {
            $htmlRoutes += "$route|0|ERROR: $($_.Exception.Message.Substring(0,50))"
        }
    }
}

Write-Output "=== HTML RESPONSES (NEED FIX) ==="
foreach ($r in $htmlRoutes) { Write-Output $r }
Write-Output "=== JSON OK: $jsonCount ==="
