/**
 * GAF ingest notifications + summary rendering.
 *
 * All three templates are INTERNAL (rep / office) — never customer-facing — so
 * they are NOT gated by CUSTOMER_EMAIL_ENABLED and fire normally.
 *
 *   gaf-report-summary   → the ordering rep gets the material cheat-sheet
 *                          (they already have the report itself from GAF).
 *   gaf-no-match-rep     → rep, on first miss: "no JN job found, create it".
 *   gaf-office-escalation→ office (rcrs@), after retries exhausted.
 */

import { emailService } from '../email-service';
import type { Measurements, MaterialSummary } from './coverage-config';

function officeNotifyEmail(): string {
  return process.env.GAF_OFFICE_NOTIFY_EMAIL || process.env.OFFICE_NOTIFY_EMAIL || 'rcrs@rcrsal.com';
}

function reviewUrl(): string {
  const base = process.env.NEXT_PUBLIC_BASE_URL || 'https://rcrsal.com';
  return `${base}/portal/gaf-reports`;
}

function measurementLine(m: Measurements): string {
  const bits: string[] = [];
  if (m.squares != null) bits.push(`${m.squares.toFixed(1)} sq`);
  if (m.predominantPitch) bits.push(`pitch ${m.predominantPitch}`);
  if (m.ridgeLengthFt != null) bits.push(`ridge ${m.ridgeLengthFt.toFixed(0)} LF`);
  if (m.hipLengthFt != null) bits.push(`hip ${m.hipLengthFt.toFixed(0)} LF`);
  if (m.valleyLengthFt != null) bits.push(`valley ${m.valleyLengthFt.toFixed(0)} LF`);
  if (m.eaveLengthFt != null) bits.push(`eave ${m.eaveLengthFt.toFixed(0)} LF`);
  if (m.rakeLengthFt != null) bits.push(`rake ${m.rakeLengthFt.toFixed(0)} LF`);
  return bits.join(' · ');
}

/** Plain-text cheat-sheet for the JobNimbus note. */
export function renderSummaryText(address: string, orderNumber: string, m: Measurements, s: MaterialSummary): string {
  const L: string[] = [];
  L.push(`GAF QuickMeasure — Material Order Cheat-Sheet`);
  L.push(`Property: ${address}  ·  Order #${orderNumber}`);
  L.push(measurementLine(m) || '(measurements unavailable)');
  L.push('');
  L.push('MATERIALS:');
  for (const line of s.lines) {
    L.push(`- ${line.qty} ${line.unit}  ${line.name}${line.estimated ? ' (est)' : ''}   [${line.basis}]`);
  }
  if (s.advisories.length) {
    L.push('');
    L.push('ADVISORIES:');
    for (const a of s.advisories) L.push(`- ${a}`);
  }
  if (s.assumptions.length) {
    L.push('');
    L.push('ASSUMPTIONS:');
    for (const a of s.assumptions) L.push(`- ${a}`);
  }
  if (s.incomplete) L.push('', '⚠ Some measurements were missing — counts may be partial.');
  L.push('', '(est) = uses an unconfirmed coverage default. Auto-generated by the RCRS portal from the QuickMeasure XML.');
  return L.join('\n');
}

/** HTML cheat-sheet for the rep email. */
export function renderSummaryHtml(address: string, orderNumber: string, m: Measurements, s: MaterialSummary): string {
  const rows = s.lines.map(l => `
    <tr>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right;font-weight:bold;white-space:nowrap;">${l.qty} ${l.unit}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;">${l.name}${l.estimated ? ' <span style="color:#b8860b;font-size:11px;">(est)</span>' : ''}</td>
      <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#888;font-size:12px;">${l.basis}</td>
    </tr>`).join('');
  const advisories = s.advisories.length
    ? `<h3 style="margin:18px 0 6px;">Advisories</h3><ul style="margin:0;padding-left:18px;color:#555;">${s.advisories.map(a => `<li>${a}</li>`).join('')}</ul>`
    : '';
  const assumptions = s.assumptions.length
    ? `<h3 style="margin:18px 0 6px;">Assumptions</h3><ul style="margin:0;padding-left:18px;color:#888;font-size:12px;">${s.assumptions.map(a => `<li>${a}</li>`).join('')}</ul>`
    : '';
  return `
  <div style="font-family:Arial,sans-serif;max-width:640px;margin:0 auto;">
    <div style="background:#000;padding:18px;text-align:center;">
      <h1 style="color:#39FF14;margin:0;font-size:20px;">Material Order Cheat-Sheet</h1>
    </div>
    <div style="padding:24px;background:#fff;color:#222;">
      <p style="margin:0 0 4px;"><strong>${address}</strong></p>
      <p style="margin:0 0 16px;color:#666;font-size:13px;">GAF QuickMeasure · Order #${orderNumber} · ${measurementLine(m) || 'measurements unavailable'}</p>
      <table style="width:100%;border-collapse:collapse;">${rows}</table>
      ${advisories}
      ${assumptions}
      ${s.incomplete ? '<p style="color:#c00;font-size:12px;margin-top:14px;">⚠ Some measurements were missing — counts may be partial.</p>' : ''}
      <p style="color:#999;font-size:11px;margin-top:18px;">(est) = uses an unconfirmed coverage default. The full measurement report is already in your GAF email and has been attached to the JobNimbus job.</p>
    </div>
  </div>`;
}

export async function sendRepSummary(params: {
  repEmail: string; repName: string; address: string; orderNumber: string;
  measurements: Measurements; summary: MaterialSummary;
}): Promise<{ success: boolean; error?: string }> {
  if (!params.repEmail) return { success: false, error: 'no rep email' };
  return emailService.send({
    template: 'gaf-report-summary',
    to: params.repEmail,
    subject: `Material summary — ${params.address}`,
    body: renderSummaryHtml(params.address, params.orderNumber, params.measurements, params.summary),
    fromName: 'RCRS QuickMeasure',
  });
}

export async function sendRepNoMatch(params: {
  repEmail: string; repName: string; address: string; orderNumber: string;
}): Promise<{ success: boolean; error?: string }> {
  if (!params.repEmail) return { success: false, error: 'no rep email' };
  const body = `
  <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
    <div style="background:#000;padding:18px;text-align:center;">
      <h1 style="color:#39FF14;margin:0;font-size:18px;">QuickMeasure — no matching job yet</h1>
    </div>
    <div style="padding:24px;background:#fff;color:#222;">
      <p>Hi ${params.repName || 'there'},</p>
      <p>Your GAF QuickMeasure report for <strong>${params.address}</strong> (Order #${params.orderNumber}) came in, but there's no JobNimbus job with a matching address yet, so it couldn't be attached automatically.</p>
      <p><strong>Create or open the JobNimbus job for this address</strong> (make sure the address matches the report) and the system will attach the report and the material summary automatically within about 15 minutes — no further action needed.</p>
      <p style="color:#888;font-size:12px;">If a job still isn't found after an hour, the office is notified so it doesn't fall through the cracks.</p>
    </div>
  </div>`;
  return emailService.send({
    template: 'gaf-no-match-rep',
    to: params.repEmail,
    subject: `Action needed — no JobNimbus job for ${params.address}`,
    body,
    fromName: 'RCRS QuickMeasure',
  });
}

export async function sendOfficeEscalation(params: {
  address: string; orderNumber: string; repName: string; repEmail: string;
}): Promise<{ success: boolean; error?: string }> {
  const body = `
  <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
    <div style="background:#c00;padding:18px;text-align:center;">
      <h1 style="color:#fff;margin:0;font-size:18px;">QuickMeasure unmatched after 1 hour</h1>
    </div>
    <div style="padding:24px;background:#fff;color:#222;">
      <p>A GAF QuickMeasure report has been waiting for a matching JobNimbus job for over an hour:</p>
      <table style="width:100%;border-collapse:collapse;margin:12px 0;">
        <tr><td style="padding:4px 8px;"><strong>Property</strong></td><td style="padding:4px 8px;">${params.address}</td></tr>
        <tr><td style="padding:4px 8px;"><strong>Order #</strong></td><td style="padding:4px 8px;">${params.orderNumber}</td></tr>
        <tr><td style="padding:4px 8px;"><strong>Rep</strong></td><td style="padding:4px 8px;">${params.repName || '—'} ${params.repEmail ? `(${params.repEmail})` : ''}</td></tr>
      </table>
      <p><strong>Two ways to fix it:</strong></p>
      <ol>
        <li>Create a JobNimbus job with the <em>matching address</em> — it will auto-attach on the next run, or</li>
        <li>Manually match it to an existing job on the review page.</li>
      </ol>
      <p style="text-align:center;margin:22px 0;">
        <a href="${reviewUrl()}" style="background:#39FF14;color:#000;padding:12px 24px;text-decoration:none;border-radius:6px;font-weight:bold;">Open GAF Review Page</a>
      </p>
      <p style="color:#888;font-size:12px;">The report stays in the queue and keeps retrying until it's attached — this is just a heads-up so nothing is lost.</p>
    </div>
  </div>`;
  return emailService.send({
    template: 'gaf-office-escalation',
    to: officeNotifyEmail(),
    subject: `[GAF] Unmatched report — ${params.address}`,
    body,
    fromName: 'RCRS QuickMeasure',
  });
}
