// Lead Distro Recalibration API
// GET: returns the most recent recalibration recommendation (generated by
// scripts/lead-distro-recalibrate.mjs). Admin UI surfaces these to the manager
// for manual review and approval — recommendations are NEVER auto-applied.
//
// To refresh: run `node scripts/lead-distro-recalibrate.mjs` from the project
// root. The script writes a dated markdown file in docs/. Set up a 90-day cron
// (e.g. Vercel Cron or a scheduled GitHub Action) for hands-off refresh.

import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/auth-service';
import fs from 'fs';
import path from 'path';

interface ParsedRecommendation {
  factor: string;
  action: string;
  delta: string;
  wonAvg: string;
  lostAvg: string;
  rationale: string;
}

function findLatestRecalibrationFile(): { filePath: string; date: string } | null {
  const docsDir = path.join(process.cwd(), 'docs');
  if (!fs.existsSync(docsDir)) return null;
  const files = fs.readdirSync(docsDir)
    .filter(f => /^lead-distro-recalibration-\d{4}-\d{2}-\d{2}\.md$/.test(f))
    .sort()
    .reverse();
  if (!files.length) return null;
  const filePath = path.join(docsDir, files[0]);
  const date = files[0].replace('lead-distro-recalibration-', '').replace('.md', '');
  return { filePath, date };
}

function parseRecommendations(markdown: string): ParsedRecommendation[] {
  const lines = markdown.split('\n');
  const recs: ParsedRecommendation[] = [];
  let inTable = false;
  for (const line of lines) {
    if (line.startsWith('| Factor |')) { inTable = true; continue; }
    if (inTable && line.startsWith('|--')) continue;
    if (inTable && !line.startsWith('|')) { inTable = false; continue; }
    if (inTable && line.startsWith('|')) {
      const cells = line.split('|').slice(1, -1).map(c => c.trim());
      if (cells.length >= 6) {
        recs.push({
          factor: cells[0].replace(/`/g, ''),
          action: cells[1].replace(/\*\*/g, ''),
          delta: cells[2],
          wonAvg: cells[3],
          lostAvg: cells[4],
          rationale: cells[5],
        });
      }
    }
  }
  return recs;
}

function parseSampleSizes(markdown: string): Record<string, number> {
  const out: Record<string, number> = {};
  const map: Record<string, string> = {
    'Closed-won': 'closedWon',
    'Closed-lost': 'closedLost',
    'Ghosted': 'ghosted',
    'Still open': 'open',
    'Pending manager pick': 'pendingPick',
  };
  for (const line of markdown.split('\n')) {
    for (const [label, key] of Object.entries(map)) {
      const m = line.match(new RegExp(`\\*\\*${label}\\*\\*:?\\s*(\\d+)`));
      if (m) out[key] = parseInt(m[1], 10);
    }
  }
  return out;
}

export async function GET(_request: NextRequest) {
  const auth = await requireAdmin();
  if (!auth.authenticated) return auth.response;

  const latest = findLatestRecalibrationFile();
  if (!latest) {
    return NextResponse.json({
      success: true,
      hasRecommendations: false,
      message: 'No recalibration analysis has been run yet. Run `node scripts/lead-distro-recalibrate.mjs` from the project root to generate the first report.',
    });
  }

  try {
    const raw = fs.readFileSync(latest.filePath, 'utf-8');
    const recommendations = parseRecommendations(raw);
    const sampleSizes = parseSampleSizes(raw);
    const totalAssignmentsMatch = raw.match(/Total assignments analyzed:\*\*\s*(\d+)/);
    const totalAssignments = totalAssignmentsMatch ? parseInt(totalAssignmentsMatch[1], 10) : 0;

    return NextResponse.json({
      success: true,
      hasRecommendations: true,
      generatedAt: latest.date,
      totalAssignments,
      sampleSizes,
      recommendations,
      markdownPath: `docs/lead-distro-recalibration-${latest.date}.md`,
    });
  } catch (err) {
    return NextResponse.json({
      success: false,
      error: err instanceof Error ? err.message : 'Failed to read recalibration file',
    }, { status: 500 });
  }
}
