/**
 * RCRS Training Content Data
 *
 * This file is auto-generated by the NotebookLM pipeline.
 * To regenerate: python rcrs-notebooklm/sync_to_portal.py
 *
 * Until content is generated, this exports empty arrays so the portal compiles.
 */

export interface TrainingContent {
  audioDeepDive?: string;
  trainingVideo?: string;
  briefVideo?: string;
  quiz?: string;
  flashcards?: string;
  studyGuide?: string;
  mindMap?: string;
  infographic?: string;
}

export interface TrainingModule {
  id: string;
  title: string;
  description: string;
  audience: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  content: TrainingContent;
}

export const TRAINING_MODULES: TrainingModule[] = [
  {
    id: 'sales-performance',
    title: 'Sales Performance Metrics',
    description: 'Learn the key metrics that drive RCRS sales success: conversion rates, inspection targets, pipeline management, and team performance analysis.',
    audience: ['all', 'sales_rep', 'manager'],
    difficulty: 'beginner',
    content: {
      quiz: '/training/quizzes/sales-performance-quiz.json',
      flashcards: '/training/flashcards/sales-performance-flashcards.json',
      studyGuide: '/training/guides/sales-performance-guide.md',
      infographic: 'sales-performance-infographic',
    },
  },
  {
    id: 'sales-mastery',
    title: 'Sales Territory & CRM Mastery',
    description: 'Master territory analysis, storm tracking, CRM pipeline management, commission structure, supplement filing, and canvassing techniques.',
    audience: ['sales_rep', 'manager'],
    difficulty: 'intermediate',
    content: {
      quiz: '/training/quizzes/sales-mastery-quiz.json',
      flashcards: '/training/flashcards/sales-mastery-flashcards.json',
      studyGuide: '/training/guides/sales-mastery-guide.md',
      infographic: 'sales-mastery-infographic',
    },
  },
  {
    id: 'platform-onboarding',
    title: 'Platform & Tools Onboarding',
    description: 'Get up to speed on the RCRS portal, Google Sheets backend, JobNimbus CRM, TeamUp calendar, GroupMe chat, and all platform tools.',
    audience: ['all'],
    difficulty: 'beginner',
    content: {
      quiz: '/training/quizzes/platform-onboarding-quiz.json',
      flashcards: '/training/flashcards/platform-onboarding-flashcards.json',
      studyGuide: '/training/guides/platform-onboarding-guide.md',
      infographic: 'platform-onboarding-infographic',
    },
  },
  {
    id: 'field-operations',
    title: 'Field Operations & Delivery',
    description: 'Learn material ordering, delivery lifecycle, loading checklists, inventory management, route planning, safety requirements, and documentation.',
    audience: ['driver', 'office_staff'],
    difficulty: 'intermediate',
    content: {
      quiz: '/training/quizzes/field-operations-quiz.json',
      flashcards: '/training/flashcards/field-operations-flashcards.json',
      studyGuide: '/training/guides/field-operations-guide.md',
      infographic: 'field-operations-infographic',
    },
  },
  {
    id: 'customer-service',
    title: 'Customer Service & Communication',
    description: 'Master response time standards, customer portal features, objection handling, insurance terminology, referral generation, and follow-up cadence.',
    audience: ['sales_rep', 'office_staff'],
    difficulty: 'beginner',
    content: {
      quiz: '/training/quizzes/customer-service-quiz.json',
      flashcards: '/training/flashcards/customer-service-flashcards.json',
      studyGuide: '/training/guides/customer-service-guide.md',
      infographic: 'customer-service-infographic',
    },
  },
  {
    id: 'admin-deep-dive',
    title: 'Administration & System Architecture',
    description: 'Deep dive into Next.js architecture, security model, Google Sheets data structure, JN sync engine, API routes, SEO, and deployment workflow.',
    audience: ['admin', 'manager'],
    difficulty: 'advanced',
    content: {
      quiz: '/training/quizzes/admin-deep-dive-quiz.json',
      flashcards: '/training/flashcards/admin-deep-dive-flashcards.json',
      studyGuide: '/training/guides/admin-deep-dive-guide.md',
      infographic: 'admin-deep-dive-infographic',
    },
  },
  {
    id: 'delivery-operations',
    title: 'Delivery Operations & Logistics',
    description: 'Complete guide to the RCRS delivery ecosystem including the 12-status lifecycle, loading procedures, vehicle capacity planning, safety protocols, QC checklists, returns workflow, and warehouse IoT systems.',
    audience: ['driver', 'office_staff', 'manager'],
    difficulty: 'intermediate',
    content: {
      quiz: '/training/quizzes/delivery-operations-quiz.json',
      flashcards: '/training/flashcards/delivery-operations-flashcards.json',
      studyGuide: '/training/guides/delivery-operations-guide.md',
    },
  },
];

export const TRAINING_PATHS = {
  sales: TRAINING_MODULES.filter(m => ['sales-performance', 'sales-mastery'].includes(m.id)),
  onboarding: TRAINING_MODULES.filter(m => m.id === 'platform-onboarding'),
  fieldOps: TRAINING_MODULES.filter(m => ['field-operations', 'delivery-operations'].includes(m.id)),
  customerService: TRAINING_MODULES.filter(m => m.id === 'customer-service'),
  adminDeepDive: TRAINING_MODULES.filter(m => m.id === 'admin-deep-dive'),
  deliveryOps: TRAINING_MODULES.filter(m => m.id === 'delivery-operations'),
};

export function getModulesForRole(role: string): TrainingModule[] {
  return TRAINING_MODULES.filter(
    m => m.audience.includes('all') || m.audience.includes(role)
  );
}

export function getContentUrl(moduleId: string, contentType: keyof TrainingContent): string | undefined {
  const mod = TRAINING_MODULES.find(m => m.id === moduleId);
  return mod?.content[contentType];
}
