'use client';

/**
 * RCRS Command Center - Finalize Meeting Page
 *
 * One-stop page for Michael/Sara to finalize Monday meeting data:
 * - Auto-generated Bible verse (editable)
 * - 7-day weather forecast (editable notes per day)
 * - Department announcements summary
 * - Rep numbers summary
 * - "Finalize Meeting Data" button -> saves to MeetingPrep + marks ready
 * - Link to launch presentation
 *
 * Access: Owner/Admin only
 */

import * as React from 'react';
import { useState, useEffect, useCallback } from 'react';
import Link from 'next/link';
import {
  BookOpen,
  Cloud,
  Sun,
  CloudRain,
  Snowflake,
  Wind,
  Megaphone,
  CheckCircle2,
  AlertCircle,
  Loader2,
  RefreshCw,
  Play,
  Save,
  Shuffle,
  Edit3,
  ChevronDown,
  ChevronUp,
  BarChart3,
  Users,
  DollarSign,
  ArrowLeft,
  ExternalLink,
  Image as ImageIcon,
  Link2,
  Check,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { PermissionGate, LoadingSpinner } from '@/components/command-center';
import { AVAILABLE_CHARTS } from '@/lib/meeting-data';
import {
  RevenueTrendChart, CommissionTrendChart, RepSalesChart,
  RepCommissionsChart, KeyMetricsChart, QuarterlyChart,
} from '@/components/command-center/MeetingCharts';
import type { ChartData } from '@/components/command-center/MeetingCharts';

// =============================================================================
// Types
// =============================================================================

interface BibleVerse {
  reference: string;
  text: string;
  theme: string;
}

interface WeatherDay {
  date: string;
  dayName: string;
  high: number;
  low: number;
  description: string;
  precipChance: number;
  windSpeed: number;
  icon: string;
  isWorkDay: boolean;
  workabilityReason?: string;
}

interface WeatherData {
  current: {
    temperature: number;
    feelsLike: number;
    description: string;
    humidity: number;
    windSpeed: number;
    icon: string;
    isWorkable: boolean;
  };
  weekForecast: WeatherDay[];
  workableDays: number;
  alerts: Array<{ headline: string; description: string }>;
  stormRisk: { level: string; message: string } | null;
}

interface RepBreakdown {
  name: string;
  inspected: number;
  damage: number;
  signed: number;
  repair: number;
  gutter: number;
  revenue: number;
  approved: number;
  goal: number;
  present: string;
}

interface TeamTotals {
  inspected: number;
  damage: number;
  signed: number;
  repair: number;
  gutter: number;
  revenue: number;
  approved: number;
}

interface Announcement {
  id: string;
  userName: string;
  title: string;
  content: string;
  category: string;
}

interface AutoGenerateData {
  meetingDate: string;
  weekNumber: number;
  suggestedVerse: BibleVerse;
  weather: WeatherData | null;
  thisWeek: {
    date: string;
    teamTotals: TeamTotals;
    repBreakdown: RepBreakdown[];
    repCount: number;
  };
  lastWeek: {
    date: string;
    teamTotals: TeamTotals;
    repBreakdown: RepBreakdown[];
    repCount: number;
  };
  comparison: {
    revenueChange: number;
    inspectedChange: number;
    signedChange: number;
    trend: 'up' | 'down' | 'flat';
  };
  ytd: {
    teamTotals: TeamTotals;
    topPerformer: { name: string; revenue: number };
  };
  announcements: {
    early: Announcement[];
    late: Announcement[];
  };
  existingPrep: {
    bibleVerse: BibleVerse | null;
    departmentNotes: Record<string, string>;
    status: string;
  } | null;
}

// =============================================================================
// Weather icon helper
// =============================================================================

function getWeatherIcon(icon: string) {
  if (icon?.includes('rain') || icon?.includes('drizzle')) return <CloudRain className="w-5 h-5 text-blue-400" />;
  if (icon?.includes('snow')) return <Snowflake className="w-5 h-5 text-cyan-300" />;
  if (icon?.includes('wind')) return <Wind className="w-5 h-5 text-zinc-400" />;
  if (icon?.includes('cloud')) return <Cloud className="w-5 h-5 text-zinc-400" />;
  return <Sun className="w-5 h-5 text-yellow-400" />;
}

// =============================================================================
// Default verse background images (Unsplash, free to use)
// =============================================================================

const VERSE_BACKGROUNDS = [
  { id: 'sunrise', label: 'Sunrise', url: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=1200&h=600&fit=crop&q=80' },
  { id: 'mountains', label: 'Mountains', url: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&h=600&fit=crop&q=80' },
  { id: 'ocean', label: 'Ocean', url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=600&fit=crop&q=80' },
  { id: 'forest', label: 'Forest', url: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&h=600&fit=crop&q=80' },
  { id: 'sky', label: 'Sky', url: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=1200&h=600&fit=crop&q=80' },
  { id: 'field', label: 'Field', url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&h=600&fit=crop&q=80' },
  { id: 'sunset', label: 'Sunset', url: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=1200&h=600&fit=crop&q=80' },
  { id: 'church', label: 'Church', url: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?w=1200&h=600&fit=crop&q=80' },
];

/** Parse [VERSE_BG:url] from specialNotes string */
function parseVerseBg(notes: string): string | null {
  const match = notes.match(/\[VERSE_BG:(.+?)\]/);
  return match ? match[1] : null;
}

/** Strip [VERSE_BG:url] from specialNotes string */
function stripVerseBg(notes: string): string {
  return notes.replace(/\s*\[VERSE_BG:.+?\]/, '').trim();
}

// =============================================================================
// Main Page Component
// =============================================================================

export default function FinalizeMeetingPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [data, setData] = useState<AutoGenerateData | null>(null);

  // Editable state
  const [verse, setVerse] = useState<BibleVerse>({ reference: '', text: '', theme: '' });
  const [verseEditing, setVerseEditing] = useState(false);
  const [verseBackground, setVerseBackground] = useState(VERSE_BACKGROUNDS[0].url);
  const [customBgUrl, setCustomBgUrl] = useState('');
  const [showBgPicker, setShowBgPicker] = useState(false);
  const [weatherNotes, setWeatherNotes] = useState<Record<string, string>>({});
  const [weatherEdits, setWeatherEdits] = useState<Record<string, { high?: number; low?: number; description?: string }>>({});
  const [deptNotes, setDeptNotes] = useState({ sales: '', operations: '', office: '', drivers: '' });
  const [specialNotes, setSpecialNotes] = useState('');
  const [showRepDetails, setShowRepDetails] = useState(false);
  const [approvedCharts, setApprovedCharts] = useState<string[]>([]);
  const [chartsOpen, setChartsOpen] = useState(false);
  const [chartData, setChartData] = useState<ChartData | null>(null);
  const [chartPeriod, setChartPeriod] = useState<'week' | 'month' | 'quarter' | 'year'>('year');
  const [chartLoading, setChartLoading] = useState(false);

  // Fetch auto-generated data
  const fetchData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/command-center/meetings/auto-generate');
      const json = await res.json();
      if (!json.success) throw new Error(json.error || 'Failed to load');

      const d = json.data as AutoGenerateData;
      setData(d);

      // Pre-fill verse from existing prep or suggested
      const existingVerse = d.existingPrep?.bibleVerse;
      setVerse(existingVerse || d.suggestedVerse || { reference: '', text: '', theme: '' });

      // Pre-fill dept notes from existing prep
      if (d.existingPrep?.departmentNotes) {
        setDeptNotes({
          sales: d.existingPrep.departmentNotes.sales || '',
          operations: d.existingPrep.departmentNotes.operations || '',
          office: d.existingPrep.departmentNotes.office || '',
          drivers: d.existingPrep.departmentNotes.drivers || '',
        });
      }

      // Pre-fill verse background from specialNotes if saved
      const existingNotes = (d.existingPrep as Record<string, unknown>)?.specialNotes as string || '';
      if (existingNotes) {
        const savedBg = parseVerseBg(existingNotes);
        if (savedBg) {
          setVerseBackground(savedBg);
          // If it's a custom URL (not in our presets), populate the custom field
          const isPreset = VERSE_BACKGROUNDS.some(bg => bg.url === savedBg);
          if (!isPreset) setCustomBgUrl(savedBg);
        }
        // Strip the [VERSE_BG:...] tag from the displayed specialNotes
        setSpecialNotes(stripVerseBg(existingNotes));
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load meeting data');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { fetchData(); }, [fetchData]);

  // Fetch chart data when charts section is opened or period changes
  useEffect(() => {
    if (!chartsOpen) return;
    setChartLoading(true);
    fetch(`/api/command-center/meetings/charts?period=${chartPeriod}`)
      .then(res => res.json())
      .then(json => { if (json.success) setChartData(json.data); })
      .catch(() => {})
      .finally(() => setChartLoading(false));
  }, [chartsOpen, chartPeriod]);

  // Shuffle to a new random verse
  const shuffleVerse = async () => {
    try {
      const res = await fetch('/api/command-center/meetings?action=verse');
      const json = await res.json();
      if (json.success && json.data) {
        setVerse(json.data);
      }
    } catch {
      // Keep current verse on error
    }
  };

  // Save and finalize
  const handleFinalize = async () => {
    if (!data) return;
    setSaving(true);
    setError(null);
    setSuccess(null);

    try {
      // Build the weather data string with notes for storage
      const weatherSummary = data.weather?.weekForecast.map(day => {
        const note = weatherNotes[day.date] ? ` | Note: ${weatherNotes[day.date]}` : '';
        const edit = weatherEdits[day.date];
        const high = edit?.high ?? day.high;
        const low = edit?.low ?? day.low;
        const desc = edit?.description ?? day.description;
        return `${day.dayName}: ${high}/${low}F ${desc}${note}`;
      }).join('\n') || '';

      // Build specialNotes with verse background tag appended
      const verseBgTag = ` [VERSE_BG:${verseBackground}]`;
      const combinedNotes = specialNotes + verseBgTag + (weatherSummary ? `\n\n--- Weather Notes ---\n${weatherSummary}` : '');

      // Save prep data
      const prepData = {
        meetingDate: data.meetingDate,
        bibleVerse: verse,
        useRandomVerse: false,
        announcements: {
          part1: data.announcements.early?.map((a: Announcement) => a.content || a.title) || [],
          part2: data.announcements.late?.map((a: Announcement) => a.content || a.title) || [],
        },
        departmentNotes: deptNotes,
        specialNotes: combinedNotes,
        preparedBy: 'Admin',
        status: 'draft',
        approvedCharts,
      };

      // Save
      const saveRes = await fetch('/api/command-center/meetings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'save-prep', data: prepData }),
      });
      const saveJson = await saveRes.json();
      if (!saveJson.success) throw new Error(saveJson.error || 'Save failed');

      // Mark as ready
      const readyRes = await fetch('/api/command-center/meetings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'mark-ready', data: { meetingDate: data.meetingDate } }),
      });
      const readyJson = await readyRes.json();
      if (!readyJson.success) throw new Error(readyJson.error || 'Failed to mark ready');

      setSuccess('Meeting data finalized! Ready for presentation.');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to finalize');
    } finally {
      setSaving(false);
    }
  };

  // Save draft only (no mark-ready)
  const handleSaveDraft = async () => {
    if (!data) return;
    setSaving(true);
    setError(null);
    setSuccess(null);

    try {
      const verseBgTag = ` [VERSE_BG:${verseBackground}]`;
      const prepData = {
        meetingDate: data.meetingDate,
        bibleVerse: verse,
        useRandomVerse: false,
        announcements: {
          part1: data.announcements.early?.map((a: Announcement) => a.content || a.title) || [],
          part2: data.announcements.late?.map((a: Announcement) => a.content || a.title) || [],
        },
        departmentNotes: deptNotes,
        specialNotes: specialNotes + verseBgTag,
        preparedBy: 'Admin',
        status: 'draft',
        approvedCharts,
      };

      const res = await fetch('/api/command-center/meetings', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'save-prep', data: prepData }),
      });
      const json = await res.json();
      if (!json.success) throw new Error(json.error || 'Save failed');

      setSuccess('Draft saved.');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save draft');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <LoadingSpinner />
        <span className="ml-3 text-zinc-400">Loading meeting data...</span>
      </div>
    );
  }

  if (error && !data) {
    return (
      <div className="max-w-4xl mx-auto p-6">
        <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-6 text-center">
          <AlertCircle className="w-8 h-8 text-red-400 mx-auto mb-2" />
          <p className="text-red-400">{error}</p>
          <button onClick={fetchData} className="mt-4 px-4 py-2 bg-zinc-700 rounded-lg hover:bg-zinc-600 text-sm">
            Retry
          </button>
        </div>
      </div>
    );
  }

  if (!data) return null;

  const meetingDateFormatted = new Date(data.meetingDate + 'T12:00:00').toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });

  return (
    <PermissionGate permissions={['dashboard.viewAll']}>
      <div className="max-w-5xl mx-auto p-4 sm:p-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <Link href="/command-center/meetings" className="text-sm text-zinc-500 hover:text-zinc-300 flex items-center gap-1 mb-2">
              <ArrowLeft className="w-4 h-4" /> Back to Meeting Hub
            </Link>
            <h1 className="text-2xl sm:text-3xl font-bold text-white">Finalize Meeting Data</h1>
            <p className="text-zinc-400 mt-1">{meetingDateFormatted} &bull; Meeting at 10:00 AM CT</p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={fetchData}
              className="flex items-center gap-2 px-3 py-2 bg-zinc-800 border border-zinc-700 rounded-lg hover:bg-zinc-700 text-sm"
            >
              <RefreshCw className="w-4 h-4" /> Refresh
            </button>
            <Link
              href="/command-center/meetings/present"
              className="flex items-center gap-2 px-4 py-2 bg-lime-500/20 border border-lime-500/40 rounded-lg hover:bg-lime-500/30 text-lime-400 text-sm font-medium"
            >
              <Play className="w-4 h-4" /> Launch Presentation
            </Link>
          </div>
        </div>

        {/* Status banner */}
        {success && (
          <div className="bg-lime-500/10 border border-lime-500/30 rounded-xl p-4 flex items-center gap-3">
            <CheckCircle2 className="w-5 h-5 text-lime-400 shrink-0" />
            <span className="text-lime-300">{success}</span>
          </div>
        )}
        {error && (
          <div className="bg-red-500/10 border border-red-500/30 rounded-xl p-4 flex items-center gap-3">
            <AlertCircle className="w-5 h-5 text-red-400 shrink-0" />
            <span className="text-red-300">{error}</span>
          </div>
        )}

        {/* ================================================================= */}
        {/* SECTION 1: Bible Verse */}
        {/* ================================================================= */}
        <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <BookOpen className="w-5 h-5 text-lime-400" /> Bible Verse
            </h2>
            <div className="flex gap-2">
              <button
                onClick={shuffleVerse}
                className="flex items-center gap-1 px-3 py-1.5 text-xs bg-zinc-800 border border-zinc-700 rounded-lg hover:bg-zinc-700"
              >
                <Shuffle className="w-3.5 h-3.5" /> New Verse
              </button>
              <button
                onClick={() => setVerseEditing(!verseEditing)}
                className="flex items-center gap-1 px-3 py-1.5 text-xs bg-zinc-800 border border-zinc-700 rounded-lg hover:bg-zinc-700"
              >
                <Edit3 className="w-3.5 h-3.5" /> {verseEditing ? 'Done' : 'Edit'}
              </button>
              <button
                onClick={() => setShowBgPicker(!showBgPicker)}
                className={cn(
                  'flex items-center gap-1 px-3 py-1.5 text-xs border rounded-lg',
                  showBgPicker
                    ? 'bg-lime-500/20 border-lime-500/40 text-lime-400'
                    : 'bg-zinc-800 border-zinc-700 hover:bg-zinc-700'
                )}
              >
                <ImageIcon className="w-3.5 h-3.5" /> Background
              </button>
            </div>
          </div>

          {verseEditing ? (
            <div className="space-y-3">
              <div>
                <label className="text-xs text-zinc-500 mb-1 block">Reference</label>
                <input
                  type="text"
                  value={verse.reference}
                  onChange={(e) => setVerse({ ...verse, reference: e.target.value })}
                  className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white"
                  placeholder="e.g. Proverbs 16:3"
                />
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1 block">Text</label>
                <textarea
                  value={verse.text}
                  onChange={(e) => setVerse({ ...verse, text: e.target.value })}
                  className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white min-h-[80px]"
                  placeholder="Verse text..."
                />
              </div>
              <div>
                <label className="text-xs text-zinc-500 mb-1 block">Theme</label>
                <input
                  type="text"
                  value={verse.theme}
                  onChange={(e) => setVerse({ ...verse, theme: e.target.value })}
                  className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white"
                  placeholder="e.g. Dedication"
                />
              </div>
            </div>
          ) : (
            /* Verse displayed over background image with dark overlay */
            <div
              className="relative w-full rounded-xl overflow-hidden"
              style={{ minHeight: '220px' }}
            >
              {/* Background image */}
              <div
                className="absolute inset-0 bg-cover bg-center"
                style={{ backgroundImage: `url(${verseBackground})` }}
              />
              {/* Dark gradient overlay for readability */}
              <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/50 to-black/70" />
              {/* Verse content */}
              <div className="relative z-10 flex flex-col items-center justify-center text-center px-8 py-10" style={{ minHeight: '220px' }}>
                <p className="text-lime-400 font-semibold text-sm mb-3 tracking-wide uppercase drop-shadow-lg">
                  {verse.reference}
                </p>
                <p className="text-white text-lg sm:text-xl italic leading-relaxed max-w-2xl drop-shadow-lg">
                  &ldquo;{verse.text}&rdquo;
                </p>
                <p className="text-zinc-300/80 text-xs mt-4 drop-shadow">Theme: {verse.theme}</p>
              </div>
            </div>
          )}

          {/* Background image picker */}
          {showBgPicker && (
            <div className="mt-4 space-y-3">
              <p className="text-xs text-zinc-500 font-medium">Choose a background image:</p>
              <div className="grid grid-cols-4 sm:grid-cols-8 gap-2">
                {VERSE_BACKGROUNDS.map((bg) => (
                  <button
                    key={bg.id}
                    onClick={() => { setVerseBackground(bg.url); setCustomBgUrl(''); }}
                    className={cn(
                      'relative rounded-lg overflow-hidden border-2 transition-all aspect-video group',
                      verseBackground === bg.url
                        ? 'border-lime-400 ring-2 ring-lime-400/30'
                        : 'border-zinc-700 hover:border-zinc-500'
                    )}
                    title={bg.label}
                  >
                    <div
                      className="absolute inset-0 bg-cover bg-center"
                      style={{ backgroundImage: `url(${bg.url.replace('w=1200&h=600', 'w=200&h=120')})` }}
                    />
                    <div className="absolute inset-0 bg-black/20 group-hover:bg-black/10 transition-colors" />
                    {verseBackground === bg.url && (
                      <div className="absolute inset-0 flex items-center justify-center">
                        <Check className="w-4 h-4 text-lime-400 drop-shadow-lg" />
                      </div>
                    )}
                    <span className="relative z-10 text-[9px] text-white font-medium drop-shadow block mt-auto pt-6 pb-0.5 text-center">
                      {bg.label}
                    </span>
                  </button>
                ))}
              </div>

              {/* Custom URL input */}
              <div className="flex items-center gap-2">
                <Link2 className="w-4 h-4 text-zinc-500 shrink-0" />
                <input
                  type="url"
                  value={customBgUrl}
                  onChange={(e) => setCustomBgUrl(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' && customBgUrl.trim()) {
                      setVerseBackground(customBgUrl.trim());
                    }
                  }}
                  className="flex-1 bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-1.5 text-xs text-white placeholder-zinc-600"
                  placeholder="Or paste a custom image URL..."
                />
                <button
                  onClick={() => { if (customBgUrl.trim()) setVerseBackground(customBgUrl.trim()); }}
                  disabled={!customBgUrl.trim()}
                  className="px-3 py-1.5 text-xs bg-zinc-700 border border-zinc-600 rounded-lg hover:bg-zinc-600 disabled:opacity-40 disabled:cursor-not-allowed text-white"
                >
                  Apply
                </button>
              </div>
            </div>
          )}
        </section>

        {/* ================================================================= */}
        {/* SECTION 2: 7-Day Weather Forecast */}
        {/* ================================================================= */}
        <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
          <h2 className="text-lg font-semibold text-white flex items-center gap-2 mb-4">
            <Cloud className="w-5 h-5 text-blue-400" /> 7-Day Weather Forecast
            {data.weather && (
              <span className="text-xs font-normal text-zinc-500 ml-2">
                {data.weather.workableDays} workable days this week
              </span>
            )}
          </h2>

          {data.weather ? (
            <>
              {/* Current conditions */}
              <div className="bg-zinc-800/50 rounded-lg p-3 mb-4 flex items-center gap-4 flex-wrap">
                <div className="flex items-center gap-2">
                  {getWeatherIcon(data.weather.current.icon)}
                  <span className="text-2xl font-bold text-white">{Math.round(data.weather.current.temperature)}&deg;F</span>
                </div>
                <div className="text-sm text-zinc-400">
                  <span>{data.weather.current.description}</span>
                  <span className="mx-2">&bull;</span>
                  <span>Feels like {Math.round(data.weather.current.feelsLike)}&deg;F</span>
                  <span className="mx-2">&bull;</span>
                  <span>Humidity {data.weather.current.humidity}%</span>
                  <span className="mx-2">&bull;</span>
                  <span>Wind {Math.round(data.weather.current.windSpeed)} mph</span>
                </div>
                {data.weather.current.isWorkable ? (
                  <span className="ml-auto text-xs bg-lime-500/20 text-lime-400 px-2 py-1 rounded">Workable</span>
                ) : (
                  <span className="ml-auto text-xs bg-red-500/20 text-red-400 px-2 py-1 rounded">Not Workable</span>
                )}
              </div>

              {/* Weather alerts */}
              {data.weather.alerts && data.weather.alerts.length > 0 && (
                <div className="bg-orange-500/10 border border-orange-500/30 rounded-lg p-3 mb-4">
                  <p className="text-orange-400 font-medium text-sm">Weather Alerts</p>
                  {data.weather.alerts.map((alert, i) => (
                    <p key={i} className="text-orange-300 text-xs mt-1">{alert.headline}</p>
                  ))}
                </div>
              )}

              {/* 7-day forecast grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                {data.weather.weekForecast.map((day) => {
                  const edit = weatherEdits[day.date] || {};
                  const displayHigh = edit.high ?? day.high;
                  const displayLow = edit.low ?? day.low;
                  const displayDesc = edit.description ?? day.description;

                  return (
                    <div
                      key={day.date}
                      className={cn(
                        'bg-zinc-800/50 rounded-lg p-3 border',
                        day.isWorkDay ? 'border-zinc-700' : 'border-red-500/30'
                      )}
                    >
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-medium text-white text-sm">{day.dayName}</span>
                        {getWeatherIcon(day.icon)}
                      </div>
                      <div className="flex items-baseline gap-1 mb-1">
                        <input
                          type="number"
                          value={displayHigh}
                          onChange={(e) => setWeatherEdits({
                            ...weatherEdits,
                            [day.date]: { ...weatherEdits[day.date], high: parseInt(e.target.value) || day.high },
                          })}
                          className="w-12 bg-transparent border-b border-zinc-600 text-white font-bold text-lg text-center focus:border-lime-400 outline-none"
                        />
                        <span className="text-zinc-500 text-xs">/</span>
                        <input
                          type="number"
                          value={displayLow}
                          onChange={(e) => setWeatherEdits({
                            ...weatherEdits,
                            [day.date]: { ...weatherEdits[day.date], low: parseInt(e.target.value) || day.low },
                          })}
                          className="w-12 bg-transparent border-b border-zinc-600 text-zinc-400 text-sm text-center focus:border-lime-400 outline-none"
                        />
                        <span className="text-zinc-500 text-xs">&deg;F</span>
                      </div>
                      <input
                        type="text"
                        value={displayDesc}
                        onChange={(e) => setWeatherEdits({
                          ...weatherEdits,
                          [day.date]: { ...weatherEdits[day.date], description: e.target.value },
                        })}
                        className="w-full bg-transparent text-zinc-400 text-xs border-b border-transparent hover:border-zinc-600 focus:border-lime-400 outline-none mb-2"
                      />
                      <div className="text-xs text-zinc-500 mb-2">
                        Rain: {day.precipChance}% &bull; Wind: {Math.round(day.windSpeed)}mph
                      </div>
                      {!day.isWorkDay && (
                        <span className="text-[10px] text-red-400 bg-red-500/10 px-1.5 py-0.5 rounded">
                          {day.workabilityReason || 'Not workable'}
                        </span>
                      )}
                      <textarea
                        placeholder="Add note..."
                        value={weatherNotes[day.date] || ''}
                        onChange={(e) => setWeatherNotes({ ...weatherNotes, [day.date]: e.target.value })}
                        className="w-full mt-2 bg-zinc-800 border border-zinc-700 rounded px-2 py-1.5 text-xs text-white placeholder-zinc-600 resize-none"
                        rows={2}
                      />
                    </div>
                  );
                })}
              </div>
            </>
          ) : (
            <div className="text-zinc-500 text-sm py-4 text-center">
              Weather data unavailable. Will retry on refresh.
            </div>
          )}
        </section>

        {/* ================================================================= */}
        {/* SECTION 3: Sales Numbers Summary */}
        {/* ================================================================= */}
        <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-purple-400" /> Sales Numbers
            </h2>
            <button
              onClick={() => setShowRepDetails(!showRepDetails)}
              className="flex items-center gap-1 px-3 py-1.5 text-xs bg-zinc-800 border border-zinc-700 rounded-lg hover:bg-zinc-700"
            >
              {showRepDetails ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
              {showRepDetails ? 'Hide' : 'Show'} Rep Details
            </button>
          </div>

          {/* Team totals */}
          <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3 mb-4">
            {[
              { label: 'Inspected', value: data.thisWeek.teamTotals.inspected, prev: data.lastWeek.teamTotals.inspected },
              { label: 'Damage', value: data.thisWeek.teamTotals.damage, prev: data.lastWeek.teamTotals.damage },
              { label: 'Signed', value: data.thisWeek.teamTotals.signed, prev: data.lastWeek.teamTotals.signed },
              { label: 'Repair', value: data.thisWeek.teamTotals.repair, prev: data.lastWeek.teamTotals.repair },
              { label: 'Gutter', value: data.thisWeek.teamTotals.gutter, prev: data.lastWeek.teamTotals.gutter },
              { label: 'Revenue', value: data.thisWeek.teamTotals.revenue, prev: data.lastWeek.teamTotals.revenue, isCurrency: true },
              { label: 'Approved', value: data.thisWeek.teamTotals.approved, prev: data.lastWeek.teamTotals.approved },
            ].map((item) => (
              <div key={item.label} className="bg-zinc-800/50 rounded-lg p-3 text-center">
                <p className="text-xs text-zinc-500 mb-1">{item.label}</p>
                <p className="text-xl font-bold text-white">
                  {item.isCurrency ? `$${item.value.toLocaleString()}` : item.value}
                </p>
                <p className={cn(
                  'text-xs mt-1',
                  item.value > item.prev ? 'text-lime-400' : item.value < item.prev ? 'text-red-400' : 'text-zinc-500'
                )}>
                  vs {item.isCurrency ? `$${item.prev.toLocaleString()}` : item.prev} last week
                </p>
              </div>
            ))}
          </div>

          {/* Trend indicator */}
          <div className="flex items-center gap-4 text-sm text-zinc-400 mb-3">
            <span>Week-over-week: Revenue {data.comparison.revenueChange > 0 ? '+' : ''}{data.comparison.revenueChange}%</span>
            <span>&bull;</span>
            <span>Inspected {data.comparison.inspectedChange > 0 ? '+' : ''}{data.comparison.inspectedChange}%</span>
            <span>&bull;</span>
            <span>Signed {data.comparison.signedChange > 0 ? '+' : ''}{data.comparison.signedChange}%</span>
          </div>

          {/* YTD summary */}
          <div className="bg-zinc-800/30 rounded-lg p-3 mb-3 flex flex-wrap items-center gap-4 text-sm">
            <span className="text-zinc-400">YTD Revenue:</span>
            <span className="text-lime-400 font-bold">${data.ytd.teamTotals.revenue.toLocaleString()}</span>
            <span className="text-zinc-600">|</span>
            <span className="text-zinc-400">Top Performer:</span>
            <span className="text-white font-medium">{data.ytd.topPerformer.name} (${data.ytd.topPerformer.revenue.toLocaleString()})</span>
          </div>

          {/* Rep breakdown */}
          {showRepDetails && data.thisWeek.repBreakdown.length > 0 && (
            <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="text-zinc-500 border-b border-zinc-800">
                    <th className="text-left py-2 px-2">Rep</th>
                    <th className="text-center py-2 px-1">Insp</th>
                    <th className="text-center py-2 px-1">Dmg</th>
                    <th className="text-center py-2 px-1">Signed</th>
                    <th className="text-center py-2 px-1">Repair</th>
                    <th className="text-center py-2 px-1">Gutter</th>
                    <th className="text-right py-2 px-2">Revenue</th>
                    <th className="text-center py-2 px-1">Appvd</th>
                  </tr>
                </thead>
                <tbody>
                  {data.thisWeek.repBreakdown.map((rep) => (
                    <tr key={rep.name} className="border-b border-zinc-800/50 hover:bg-zinc-800/30">
                      <td className="py-2 px-2 text-white font-medium">{rep.name}</td>
                      <td className="py-2 px-1 text-center text-zinc-300">{rep.inspected}</td>
                      <td className="py-2 px-1 text-center text-zinc-300">{rep.damage}</td>
                      <td className="py-2 px-1 text-center text-zinc-300">{rep.signed}</td>
                      <td className="py-2 px-1 text-center text-zinc-300">{rep.repair}</td>
                      <td className="py-2 px-1 text-center text-zinc-300">{rep.gutter}</td>
                      <td className="py-2 px-2 text-right text-lime-400 font-medium">${rep.revenue.toLocaleString()}</td>
                      <td className="py-2 px-1 text-center text-zinc-300">{rep.approved}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {data.thisWeek.repBreakdown.length === 0 && (
            <div className="text-zinc-500 text-sm py-3 text-center bg-zinc-800/30 rounded-lg">
              No rep numbers submitted yet for this week. Numbers will appear here as reps enter them during the meeting.
            </div>
          )}
        </section>

        {/* ================================================================= */}
        {/* SECTION 4: Announcements */}
        {/* ================================================================= */}
        <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
          <h2 className="text-lg font-semibold text-white flex items-center gap-2 mb-4">
            <Megaphone className="w-5 h-5 text-orange-400" /> Announcements
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <h3 className="text-sm font-medium text-zinc-400 mb-2">Part 1 (Early)</h3>
              {data.announcements.early && data.announcements.early.length > 0 ? (
                <div className="space-y-2">
                  {data.announcements.early.map((a: Announcement, i: number) => (
                    <div key={i} className="bg-zinc-800/50 rounded-lg p-3 text-sm">
                      <p className="text-white">{a.title || a.content}</p>
                      <p className="text-zinc-500 text-xs mt-1">{a.userName} &bull; {a.category}</p>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-zinc-600 text-sm">No early announcements submitted.</p>
              )}
            </div>
            <div>
              <h3 className="text-sm font-medium text-zinc-400 mb-2">Part 2 (Late)</h3>
              {data.announcements.late && data.announcements.late.length > 0 ? (
                <div className="space-y-2">
                  {data.announcements.late.map((a: Announcement, i: number) => (
                    <div key={i} className="bg-zinc-800/50 rounded-lg p-3 text-sm">
                      <p className="text-white">{a.title || a.content}</p>
                      <p className="text-zinc-500 text-xs mt-1">{a.userName} &bull; {a.category}</p>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-zinc-600 text-sm">No late announcements submitted.</p>
              )}
            </div>
          </div>
        </section>

        {/* ================================================================= */}
        {/* SECTION 5: Department Notes */}
        {/* ================================================================= */}
        <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
          <h2 className="text-lg font-semibold text-white flex items-center gap-2 mb-4">
            <Users className="w-5 h-5 text-cyan-400" /> Department Notes
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {(['sales', 'operations', 'office', 'drivers'] as const).map((dept) => (
              <div key={dept}>
                <label className="text-xs text-zinc-500 mb-1 block capitalize">{dept}</label>
                <textarea
                  value={deptNotes[dept]}
                  onChange={(e) => setDeptNotes({ ...deptNotes, [dept]: e.target.value })}
                  className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white placeholder-zinc-600 resize-none"
                  rows={3}
                  placeholder={`${dept.charAt(0).toUpperCase() + dept.slice(1)} notes for this meeting...`}
                />
              </div>
            ))}
          </div>
          <div className="mt-4">
            <label className="text-xs text-zinc-500 mb-1 block">Special Notes</label>
            <textarea
              value={specialNotes}
              onChange={(e) => setSpecialNotes(e.target.value)}
              className="w-full bg-zinc-800 border border-zinc-700 rounded-lg px-3 py-2 text-sm text-white placeholder-zinc-600 resize-none"
              rows={2}
              placeholder="Any additional notes for the meeting..."
            />
          </div>
        </section>

        {/* ================================================================= */}
        {/* SECTION 6: Charts Approval */}
        {/* ================================================================= */}
        <section className="bg-zinc-900 border border-zinc-800 rounded-xl p-5">
          <button
            onClick={() => setChartsOpen(!chartsOpen)}
            className="w-full flex items-center justify-between"
          >
            <h2 className="text-lg font-semibold text-white flex items-center gap-2">
              <BarChart3 className="w-5 h-5 text-lime-400" /> Charts for Presentation
              <span className="text-xs font-normal text-zinc-500 ml-2">
                ({approvedCharts.length}/{AVAILABLE_CHARTS.length} approved)
              </span>
            </h2>
            {chartsOpen ? <ChevronUp className="w-5 h-5 text-zinc-500" /> : <ChevronDown className="w-5 h-5 text-zinc-500" />}
          </button>

          {chartsOpen && (
            <div className="mt-4 space-y-4">
              {/* Chart approval checkboxes */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {AVAILABLE_CHARTS.map((chart) => (
                  <label
                    key={chart.id}
                    className={cn(
                      'flex items-start gap-3 p-3 rounded-lg border cursor-pointer transition',
                      approvedCharts.includes(chart.id)
                        ? 'bg-lime-500/10 border-lime-500/40'
                        : 'bg-zinc-800 border-zinc-700 hover:border-zinc-600'
                    )}
                  >
                    <input
                      type="checkbox"
                      checked={approvedCharts.includes(chart.id)}
                      onChange={(e) => {
                        if (e.target.checked) {
                          setApprovedCharts([...approvedCharts, chart.id]);
                        } else {
                          setApprovedCharts(approvedCharts.filter(id => id !== chart.id));
                        }
                      }}
                      className="mt-0.5 accent-lime-500"
                    />
                    <div>
                      <span className="text-sm font-medium text-white">{chart.name}</span>
                      <p className="text-xs text-zinc-500">{chart.description}</p>
                    </div>
                  </label>
                ))}
              </div>

              {/* Quick actions */}
              <div className="flex gap-2">
                <button
                  onClick={() => setApprovedCharts(AVAILABLE_CHARTS.map(c => c.id))}
                  className="text-xs px-3 py-1.5 bg-zinc-800 border border-zinc-700 rounded-lg hover:bg-zinc-700 text-zinc-300"
                >
                  Select All
                </button>
                <button
                  onClick={() => setApprovedCharts([])}
                  className="text-xs px-3 py-1.5 bg-zinc-800 border border-zinc-700 rounded-lg hover:bg-zinc-700 text-zinc-300"
                >
                  Clear All
                </button>
              </div>

              {/* Period toggle for preview */}
              <div className="flex items-center gap-2">
                <span className="text-xs text-zinc-500">Preview period:</span>
                {(['week', 'month', 'quarter', 'year'] as const).map(p => (
                  <button
                    key={p}
                    onClick={() => setChartPeriod(p)}
                    className={cn(
                      'px-3 py-1 text-xs font-medium rounded-md transition',
                      chartPeriod === p ? 'bg-lime-500 text-black' : 'bg-zinc-800 text-zinc-400 hover:text-white'
                    )}
                  >
                    {p === 'week' ? 'Week' : p === 'month' ? 'Month' : p === 'quarter' ? 'Quarter' : 'Year'}
                  </button>
                ))}
              </div>

              {/* Chart previews */}
              {chartLoading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="w-6 h-6 text-lime-400 animate-spin" />
                  <span className="ml-2 text-sm text-zinc-400">Loading charts...</span>
                </div>
              ) : chartData ? (
                <div className="space-y-4">
                  {approvedCharts.includes('revenue-trend') && (
                    <RevenueTrendChart data={chartData.revenueTrend} height={250} />
                  )}
                  {approvedCharts.includes('commission-trend') && (
                    <CommissionTrendChart data={chartData.commissionTrend} height={250} />
                  )}
                  {approvedCharts.includes('rep-sales') && (
                    <RepSalesChart data={chartData.repSales} height={300} />
                  )}
                  {approvedCharts.includes('rep-commissions') && (
                    <RepCommissionsChart data={chartData.repCommissions} height={300} />
                  )}
                  {approvedCharts.includes('key-metrics') && (
                    <KeyMetricsChart data={chartData.keyMetrics} height={250} />
                  )}
                  {approvedCharts.includes('quarterly') && (
                    <QuarterlyChart data={chartData.quarterly} height={250} />
                  )}
                  {approvedCharts.length === 0 && (
                    <p className="text-sm text-zinc-500 text-center py-4">
                      Select charts above to preview them. Only approved charts will appear in the presentation.
                    </p>
                  )}
                </div>
              ) : null}
            </div>
          )}
        </section>

        {/* ================================================================= */}
        {/* ACTION BUTTONS */}
        {/* ================================================================= */}
        <div className="flex items-center justify-between flex-wrap gap-4 pb-8">
          <div className="flex gap-3">
            <button
              onClick={handleSaveDraft}
              disabled={saving}
              className="flex items-center gap-2 px-5 py-3 bg-zinc-800 border border-zinc-700 rounded-xl hover:bg-zinc-700 text-sm font-medium disabled:opacity-50"
            >
              {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
              Save Draft
            </button>
            <button
              onClick={handleFinalize}
              disabled={saving}
              className="flex items-center gap-2 px-6 py-3 bg-lime-500 text-black rounded-xl hover:bg-lime-400 text-sm font-bold disabled:opacity-50"
            >
              {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <CheckCircle2 className="w-4 h-4" />}
              Finalize Meeting Data
            </button>
          </div>
          <Link
            href="/command-center/meetings/present"
            className="flex items-center gap-2 px-5 py-3 bg-blue-600 text-white rounded-xl hover:bg-blue-500 text-sm font-medium"
          >
            <Play className="w-4 h-4" /> Launch Presentation <ExternalLink className="w-3.5 h-3.5" />
          </Link>
        </div>
      </div>
    </PermissionGate>
  );
}
