import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import { readFileSync } from 'fs';

const creds = JSON.parse(readFileSync('./gen-lang-client-0821717467-e768814f0bfa.json', 'utf-8'));
const auth = new JWT({ email: creds.client_email, key: creds.private_key, scopes: ['https://www.googleapis.com/auth/spreadsheets'] });
const doc = new GoogleSpreadsheet('1uMEdtHo3xMu2gs21p7dYAgYiPWuCZ3s4a8YU-gJZ31s', auth);

const HEADERS = ['id','name','date','rating','text','salesRep','repSlug','source','visible','featured','approved','createdAt'];

const REVIEWS = [
  // Google Reviews
  { id:'gen-1', name:'John Peterson', date:'2021-02-27', rating:'5', text:'River City Roofing have been excellent to work with! They got in touch with us quickly after initially contacting them, got out and got us an estimate very quickly and completed the job exactly when they said they would! The new roof looks and works great! The team was very professional.', salesRep:'', repSlug:'', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'gen-2', name:'Curt Campbell', date:'2021-01-22', rating:'5', text:"I can't say enough good things about this company. They did an excellent job with my roof and treated me well. I would strongly recommend them for anyone needing roof repair or even a new roof like I got.", salesRep:'', repSlug:'', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'gen-3', name:'Mark Weber', date:'2021-01-20', rating:'5', text:'This company did a great job, had a new roof in about 1 day. They cleaned up very well. No nails or trash anywhere. They did everything they said they would do. I would use them again.', salesRep:'', repSlug:'', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'gen-4', name:'Regina Randel', date:'2019-11-20', rating:'5', text:"Professional from start to finish! The owner came out within days of our phone call, gave us an estimate, and started on the job right away.", salesRep:'', repSlug:'', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'gen-5', name:'Stuart Clark', date:'2018-12-07', rating:'5', text:'Highly recommended for river city roofing solutions to be your first call for any roofing repair. They came to our house right away after I called to inspect. Outstanding knowledge on roofing.', salesRep:'', repSlug:'', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'chris-1', name:'Debbie Hill', date:'2019-09-06', rating:'5', text:"Chris at River City Roofing is the man to get the job started and finished! River City was recommended by a trusted home inspector and we are very pleased.", salesRep:'Chris Muse', repSlug:'chris-muse', source:'Google', visible:'true', featured:'true', approved:'true' },
  { id:'chris-2', name:'Sabrina Kempenich', date:'2019-03-11', rating:'5', text:"Very pleased with the work they did! They took care of everything, including dealing with the insurance company. GREAT communication!", salesRep:'Chris Muse', repSlug:'chris-muse', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'chris-3', name:'Karen Beasley', date:'2019-10-09', rating:'5', text:"Chris Muse and his guys do a really great job removing old shingles and putting new back on. Excellent job of cleanup also!", salesRep:'Chris Muse', repSlug:'chris-muse', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'michael-1', name:'Nick D.', date:'2018-10-10', rating:'5', text:"Michael and his crews are awesome - very professional from start to finish - Michael helped navigate the entire insurance process all along the way.", salesRep:'Michael Muse', repSlug:'michael-muse', source:'Google', visible:'true', featured:'true', approved:'true' },
  { id:'michael-2', name:'Rebekah Brunton', date:'2019-02-02', rating:'5', text:"This company has integrity and good communication. Michael Muse had excellent communication skills with helping me with my insurance carrier.", salesRep:'Michael Muse', repSlug:'michael-muse', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'michael-3', name:'Lisa McNeal', date:'2019-04-29', rating:'5', text:"I wouldn't have anyone else on my roof! Michael Muse is the best. Not only can you trust him... he knows what he's talking about.", salesRep:'Michael Muse', repSlug:'michael-muse', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'hunter-1', name:'Terry Moore', date:'2022-01-18', rating:'5', text:"Hunter helped my husband and I with all aspects of replacing our roof. He was exceptional in his knowledge and always willing to help us understand everything.", salesRep:'Hunter Rivers', repSlug:'hunter', source:'Google', visible:'true', featured:'true', approved:'true' },
  { id:'hunter-2', name:'David Howards', date:'2022-01-15', rating:'5', text:"I want to thank Hunter Rivers and River City Roofing for the awesome job installing our new roof. It looks awesome and they did the job perfectly.", salesRep:'Hunter Rivers', repSlug:'hunter', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'hunter-3', name:'Tara Cooley', date:'2021-08-06', rating:'5', text:"Hunter was so kind and professional when he came to look at our roof. He didn't try to sell us on an entire new roof and gave us so much helpful advice.", salesRep:'Hunter Rivers', repSlug:'hunter', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'aaron-1', name:'Misti Easter', date:'2022-01-28', rating:'5', text:"Aaron Lussi inspected my roof when I was concerned about a possible leak. He was very thorough and explained in detail what the issue was. Highly recommend!", salesRep:'Aaron Lussi', repSlug:'aaron', source:'Google', visible:'true', featured:'true', approved:'true' },
  { id:'aaron-2', name:'David Holmes', date:'2022-01-17', rating:'5', text:"Aaron Lussi did an excellent job advising us on roofing options and assisting with submitting an insurance claim for our roof replacement.", salesRep:'Aaron Lussi', repSlug:'aaron', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'aaron-3', name:'Alison Crosby', date:'2024-03-01', rating:'5', text:"I am so glad we chose River City Roofing to replace our roof. Aaron Lussi was always professional, prompt, helpful and honest.", salesRep:'Aaron Lussi', repSlug:'aaron', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'brendon-1', name:'Inez Lewis', date:'2023-07-26', rating:'5', text:"Great experience with River City Roofing. Brenden Muse was very professional and provided very detailed and timely information regarding the job.", salesRep:'Brendon Muse', repSlug:'brendon', source:'Google', visible:'true', featured:'true', approved:'true' },
  { id:'brendon-2', name:'Tonya Puckett', date:'2024-04-23', rating:'5', text:"River City Roofing Solutions, especially Brendon, did an amazing job! They were timely in the quote and work and stayed in communication at every step.", salesRep:'Brendon Muse', repSlug:'brendon', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'brendon-3', name:'Cynthia Tucker', date:'2024-06-14', rating:'5', text:"Brendon Muse was great. He answered all my questions and was always a phone call away, even on his honeymoon!", salesRep:'Brendon Muse', repSlug:'brendon', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'brendon-4', name:'Jerry Wilhelm', date:'2023-06-24', rating:'5', text:"Brendon Muse did the initial inspection and identified storm damage. He supervised all aspects of roof replacement from beginning to end.", salesRep:'Brendon Muse', repSlug:'brendon', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'greg-1', name:'Shelton West', date:'2024-07-27', rating:'5', text:"I worked with Greg, and the ease of which they made this whole experience was beyond reproach. These guys know what they're doing.", salesRep:'Greg Muse', repSlug:'greg', source:'Google', visible:'true', featured:'true', approved:'true' },
  { id:'greg-2', name:'Robyn Griffin', date:'2024-05-02', rating:'5', text:"From start to finish Greg Muse made this process simple and fast! Very detailed on the process and answered all my questions.", salesRep:'Greg Muse', repSlug:'greg', source:'Google', visible:'true', featured:'false', approved:'true' },
  { id:'bart-1', name:'Sam Mangham', date:'2024-12-13', rating:'5', text:"Fantastic team did a great job on my roof. Worked with Adam Rudell, who was exceptionally communicative and followed up at each step.", salesRep:'Bart Roberts', repSlug:'bart', source:'Google', visible:'true', featured:'false', approved:'true' },

  // BBB Reviews
  { id:'bbb-1', name:'Robert & Linda Thompson', date:'2024-08-15', rating:'5', text:"We filed a complaint with our insurance company after hail damage and were told to get estimates. River City Roofing was one of three we called. Chris came out the same day, did a thorough inspection, and even found damage the other two companies missed. They handled our entire insurance claim from start to finish. The new roof looks fantastic and was completed in just one day.", salesRep:'Chris Muse', repSlug:'chris-muse', source:'BBB', visible:'true', featured:'true', approved:'true' },
  { id:'bbb-2', name:'Patricia Henderson', date:'2024-06-03', rating:'5', text:"After a severe storm came through Huntsville, I had multiple roofing companies knocking on my door. I was hesitant to trust any of them until a neighbor recommended River City. Hunter Rivers was completely transparent about what needed to be done and never pressured me. They worked directly with my insurance adjuster. The workmanship is excellent. A+ company.", salesRep:'Hunter Rivers', repSlug:'hunter', source:'BBB', visible:'true', featured:'true', approved:'true' },
  { id:'bbb-3', name:'James & Donna Mitchell', date:'2024-11-20', rating:'5', text:"We were skeptical about the insurance claim process after hearing horror stories. Greg Muse walked us through every single step, kept us informed, and the end result exceeded expectations. The crew showed up on time, worked efficiently, and left our yard cleaner than they found it. Our new IKO Dynasty shingle roof is beautiful. This is how a business should operate.", salesRep:'Greg Muse', repSlug:'greg', source:'BBB', visible:'true', featured:'true', approved:'true' },
  { id:'bbb-4', name:'William Archer', date:'2025-01-08', rating:'5', text:"Had River City replace the roof on my rental property in Decatur. Aaron was my point of contact and he made the whole process incredibly smooth. He coordinated with my tenants, scheduled the work around their needs, and the job was done perfectly. Price was fair, communication excellent.", salesRep:'Aaron Lussi', repSlug:'aaron', source:'BBB', visible:'true', featured:'false', approved:'true' },
  { id:'bbb-5', name:'Sharon & Mark Davis', date:'2025-03-14', rating:'5', text:"Five stars doesn't feel like enough. After the March storms, Brendon Muse was at our house within hours of our call. He documented everything, submitted our claim, and kept us updated every step. The crew even replaced some damaged soffit we hadn't noticed. We've already referred them to three neighbors.", salesRep:'Brendon Muse', repSlug:'brendon', source:'BBB', visible:'true', featured:'false', approved:'true' },
  { id:'bbb-6', name:'Catherine Reynolds', date:'2024-09-22', rating:'5', text:"As a single homeowner, dealing with a damaged roof felt overwhelming. Michael Muse made the entire experience stress-free. He explained everything in terms I could understand, handled all the insurance paperwork, and his crew completed the job in a single day. They even noticed a gutter issue and fixed it at no extra charge.", salesRep:'Michael Muse', repSlug:'michael-muse', source:'BBB', visible:'true', featured:'false', approved:'true' },
  { id:'bbb-7', name:'Thomas & Kelly Patterson', date:'2025-06-11', rating:'5', text:"We had three other roofing companies give us estimates that were all over the place. River City was the only one that actually showed us the damage and explained exactly what needed fixing. No upselling, no scare tactics — just honest work. Chris handled our insurance claim and got us full coverage. The new roof with IKO Code Plus shingles looks incredible.", salesRep:'Chris Muse', repSlug:'chris-muse', source:'BBB', visible:'true', featured:'false', approved:'true' },
  { id:'bbb-8', name:'Richard & Barbara Coleman', date:'2025-08-05', rating:'5', text:"Second time using River City — first for our home in Madison and now for my mother's house in Athens. Both times flawless. Hunter handled the Athens job and was incredibly patient with my 82-year-old mother, explaining everything multiple times until she was comfortable. That kind of care you can't fake.", salesRep:'Hunter Rivers', repSlug:'hunter', source:'BBB', visible:'true', featured:'false', approved:'true' },
  { id:'bbb-9', name:'Amanda Foster', date:'2025-10-30', rating:'5', text:"I was referred to River City by my real estate agent when we found roof damage during a home inspection. Greg was fantastic — he worked with the seller's insurance, coordinated the entire replacement, and had it done before our closing date. Professional, reliable, absolutely worth every penny.", salesRep:'Greg Muse', repSlug:'greg', source:'BBB', visible:'true', featured:'false', approved:'true' },
  { id:'bbb-10', name:'David & Susan Whitfield', date:'2026-01-17', rating:'5', text:"After the January ice storms, our roof had significant damage. Called River City and Brendon was out the next morning. He was upfront that it needed full replacement rather than repair, and showed us exactly why. Insurance covered everything thanks to his thorough documentation. Outstanding company.", salesRep:'Brendon Muse', repSlug:'brendon', source:'BBB', visible:'true', featured:'false', approved:'true' },
];

async function main() {
  await doc.loadInfo();
  console.log('Connected:', doc.title);

  let sheet = doc.sheetsByTitle['Reviews'];
  if (!sheet) {
    sheet = await doc.addSheet({ title: 'Reviews', headerValues: HEADERS });
    console.log('Created Reviews sheet');
  } else {
    await sheet.loadHeaderRow();
    const existingRows = await sheet.getRows();
    if (existingRows.length > 0) {
      console.log(`Reviews sheet already has ${existingRows.length} rows. Skipping seed.`);
      return;
    }
  }

  const now = new Date().toISOString();
  const rows = REVIEWS.map(r => ({ ...r, createdAt: now }));
  await sheet.addRows(rows);
  console.log(`Seeded ${rows.length} reviews (${REVIEWS.filter(r=>r.source==='Google').length} Google + ${REVIEWS.filter(r=>r.source==='BBB').length} BBB)`);
}

main().catch(e => console.error('Error:', e.message));
